const error = {
    // ! USER

    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_IMG_NOT_FOUND: 'USER_IMG_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_EMAIL_NOT_FOUND: 'USER_EMAIL_NOT_FOUND',
    USER_PASSWORD_NOTCORRECT: 'USER_PASSWORD_NOTCORRECT',
    USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
    INVALID_LOGIN_OR_PASSWORD: 'INVALID_LOGIN_OR_PASSWORD',
    USER_PHONE_NUMBER_NOT_FOUND: 'USER_PHONE_NUMBER_NOT_FOUND',
    USER_USERNAME_ALREADY_EXISTS: 'USER_USERNAME_ALREADY_EXISTS',
    USER_PHONE_NUMBER_ALREADY_EXISTS: 'USER_PHONE_NUMBER_ALREADY_EXISTS',
    EMAIL_PHONE_OR_USERNAME_REQUIRED: 'EMAIL_PHONE_OR_USERNAME_REQUIRED',

    // ! USER

    // ! AUTHORIZATION
    
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    
    // ! AUTHORIZATION
};

module.exports = {
    error,
};
